"""
base.py (docstring generated by DuetAI).

This module contains the base class for all models in the Flames POS
application. The base class provides a declarative way to define
database tables using SQLAlchemy.
"""

# import ORM base class
from sqlalchemy.orm import DeclarativeBase


# initialize derived DeclarativeBase
class Base(DeclarativeBase):
    pass
