"""
config.py (docstring generated by DuetAI).

This module contains the configuration settings for the Flames POS application.
"""

from datetime import timedelta


class Config(object):
    DEBUG = False
    TESTING = False
    PERMANENT_SESSION_LIFETIME = timedelta(minutes=30)
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SUPERADMIN_CREDS = {
        "username": "superadmin",
        "password": "admin123",
    }
    ADMIN_DEFAULT_CREDS = {
        "username": "admin",
        "password": "Pi$$a@456",
        "name": "Flames POS Administrator",
        "mobile_no": "0121231234",
        "role": "admin",
    }


class ProductionConfig(Config):
    SQLALCHEMY_DATABASE_URI = "sqlite:///flames.db"
    SECRET_KEY = "45401e953dc0f2a392aa2261691d39da0d01f60541472f85bda7bbee175e3066"


class DevelopmentConfig(Config):
    SQLALCHEMY_DATABASE_URI = "sqlite:///:memory:"
    SECRET_KEY = "f79bb0dd43c8989272b431953d74deed6fc7898ca1f2fc2e7c7b9755363fc72b"
    DEBUG = True
