"""
data.py (docstring generated by DuetAI).

This module contains variables for data used to dummy-fill the Flames POS Application database.
"""

product_names = {
    "pizza": [
        "Margherita Supreme",
        "Pepperoni Passion",
        "Veggie Delight",
        "BBQ Chicken Feast",
        "Hawaiian Paradise",
    ],
    "pasta": [
        "Spaghetti Bolognese",
        "Alfredo Eleganza",
        "Pesto Perfection",
        "Shrimp Scampi Sensation",
        "Carbonara Classic",
    ],
    "toppings": [
        "Extra Cheese Blend",
        "Sliced Olives",
        "Jalapeño Heaven",
        "Mushrooms Galore",
        "Crispy Bacon Bits",
    ],
    "salads": [
        "Caesar Crunch",
        "Greek Goddess",
        "Garden Fresh Medley",
        "Caprese Bliss",
        "Spinach Strawberry Symphony",
    ],
    "appetizers": [
        "Garlic Knots Delight",
        "Stuffed Jalapeño Poppers",
        "Mozzarella Stick Marvel",
        "Crispy Calamari Crunch",
        "Buffalo Wing Bonanza",
    ],
}

product_descriptions = {
    "pizza": [
        "A classic pizza topped with fresh tomatoes, mozzarella, and basil.",
        "Indulge in the bold flavors of pepperoni and melted cheese on a crispy crust.",
        "A vegetarian delight with a medley of colorful and savory veggies.",
        "Savor the smoky goodness of BBQ chicken on a pizza masterpiece.",
        "Transport your taste buds to a tropical paradise with ham and pineapple.",
    ],
    "pasta": [
        "Traditional Italian spaghetti served with rich and savory Bolognese sauce.",
        "Creamy Alfredo pasta topped with a sprinkle of parmesan cheese.",
        "Enjoy the aromatic flavors of basil and pine nuts in a delightful pesto pasta.",
        "A seafood lover's dream with succulent shrimp in a garlic butter sauce.",
        "Experience the timeless taste of carbonara with crispy bacon and creamy sauce.",
    ],
    "toppings": [
        "Enhance your pizza experience with an extra blend of melted cheeses.",
        "Add a burst of briny and flavorful sliced olives to your favorite dish.",
        "Turn up the heat with the spicy kick of jalapeños on your pizza or pasta.",
        "Elevate your pizza with the earthy and umami-rich flavor of mushrooms.",
        "Crispy bacon bits that add a savory and crunchy touch to any dish.",
    ],
    "salads": [
        "A crunchy and classic Caesar salad with crisp lettuce and zesty dressing.",
        "A refreshing Greek salad with feta cheese, olives, and Mediterranean flavors.",
        "A colorful and nutritious medley of garden-fresh vegetables.",
        "Indulge in the blissful combination of tomatoes, mozzarella, and basil.",
        "A symphony of flavors with spinach, strawberries, and a balsamic glaze.",
    ],
    "appetizers": [
        "Delight in the savory goodness of garlic knots, perfect for sharing.",
        "Spicy and cheesy jalapeño poppers that pack a flavorful punch.",
        "Irresistible mozzarella sticks with a golden crispy coating.",
        "Crispy calamari rings served with a zesty dipping sauce.",
        "A bonanza of buffalo wings with a choice of mouthwatering sauces.",
    ],
}
