"""
enums.py (docstring generated by DuetAI).

This module contains the enums used in the Flames POS application models.
"""

import enum


class UserRole(enum.Enum):
    owner = "owner"
    admin = "admin"
    manager = "manager"
    cashier = "cashier"


class StaffRole(enum.Enum):
    manager = "manager"
    chef = "chef"
    cook = "cook"
    driver = "driver"
    waiter = "waiter"


class PaymentType(enum.Enum):
    cash = "cash"
    card = "card"
    online = "online"
    cash_on_delivery = "cash_on_delivery"


class OrderStatus(enum.Enum):
    pending = "pending"
    confirmed = "confirmed"
    in_progress = "in_progress"
    out_for_delivery = "out_for_delivery"
    delivered = "delivered"
    cancelled = "cancelled"
    completed = "completed"
    on_hold = "on_hold"
    returned = "returned"
    refunded = "refunded"
    awaiting_pickup = "awaiting_pickup"


class Categories(enum.Enum):
    pizza = "pizza"
    pasta = "pasta"
    toppings = "toppings"
    salads = "salads"
    appetizers = "appetizers"
